[package]
name = "rust-study-rsnake"
version = "0.1.0"
authors = ["jiangcihuo <chiang-fire@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.89.0"
find_folder = "0.3.0"
rand = "0.6.5"
