[package]
name = "rust-study-test-lazy-static"
version = "0.1.0"
authors = ["jiangcihuo <chiang-fire@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"