[package]
name = "hw_01_data_type"
version = "0.1.0"
authors = ["chiangfire <chiang-fire@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
